micronaut:
  application:
    name: learnproject
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
---
micronaut:
  security:
    enabled: true
---
credentials:
  users:
    leandro: sneezy
    simone: bashful
    admin: grumpy
  roles:
    leandro: VIEW
    simone: VIEW
    admin: ADMIN
